name: Generar QR Code

on:
  push:
    branches:
      - main  # Se ejecutar치 cada vez que hagas un push en la rama "main"

jobs:
  generate_qr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4  # Versi칩n actualizada

      - name: Instalar dependencias
        run: pip install qrcode[pil]

      - name: Generar c칩digo QR
        run: |
          python -c "
          import qrcode;
          img = qrcode.make('https://jlmelo98.github.io/Algo-rico-pal-hambre-/');
          img.save('qr_code.png')"

      - name: Subir QR como artefacto
        uses: actions/upload-artifact@v4  # Versi칩n actualizada
        with:
          name: qr_code
          path: qr_code.png

